// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX8_atUvfSnVLClVStoegMmg00VfpLsUo',
    appId: '1:229115499108:web:cc135bf86ca72fc7f78571',
    messagingSenderId: '229115499108',
    projectId: 'alerta-a46a8',
    authDomain: 'alerta-a46a8.firebaseapp.com',
    storageBucket: 'alerta-a46a8.appspot.com',
    measurementId: 'G-HGNBN2SRFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTiHIL3pys-KFqVGIg49bfWO7hpABZHrc',
    appId: '1:229115499108:android:e5d9fdc7949d6271f78571',
    messagingSenderId: '229115499108',
    projectId: 'alerta-a46a8',
    storageBucket: 'alerta-a46a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9O6jMrVZrVfpxXkcXYhpm1GTvPN49N0g',
    appId: '1:229115499108:ios:232c1a7ec057ee13f78571',
    messagingSenderId: '229115499108',
    projectId: 'alerta-a46a8',
    storageBucket: 'alerta-a46a8.appspot.com',
    iosBundleId: 'com.example.untitled3',
  );
}
